name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    # Use the chgray_repo:pandoc Docker container - this containers Dockerfile is part of this enlistment and
    # contains the build tools to support pandoc and related document production tooling
    runs-on: ubuntu-latest
    container: chgray123/chgray_repro:pandoc
    #container: ubuntu:20.04   <-- alternative docker, that doesnt contain pandoc (included for reference of a blank slate)

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0

    # Print environment variables, useful for CI/CD debugging - should things go wrong
    - name: Print Environment Variables (useful in debugging CI/CD)
      run: printenv

    # Print files variables, useful for CI/CD debugging - should things go wrong
    - name: Print Files (useful in debugging CI/CD)
      run: find .

    # Configure CMake to use the /build directory to construct Makefiles
    - name: Create Build Environment
      run: cmake -E make_directory $GITHUB_WORKSPACE/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    # Actually do the build
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    # Print final files, useful for CI/CD debugging - should things go wrong
    - name: Print Final Files (useful in debugging CI/CD)
      run: find .